Transacao.create(tipo: 1, descricao: 'Débito', natureza: 'Entrada', sinal: '+')
Transacao.create(tipo: 2, descricao: 'Boleto', natureza: 'Saída', sinal: '-')
Transacao.create(tipo: 3, descricao: 'Financiamento', natureza: 'Saída	', sinal: '-')
Transacao.create(tipo: 4, descricao: 'Crédito', natureza: 'Entrada', sinal: '+')
Transacao.create(tipo: 5, descricao: 'Recebimento Empréstimo	', natureza: 'Entrada', sinal: '+')
Transacao.create(tipo: 6, descricao: 'Vendas', natureza: 'Entrada', sinal: '+')
Transacao.create(tipo: 7, descricao: 'Recebimento TED	', natureza: 'Entrada', sinal: '+')
Transacao.create(tipo: 8, descricao: 'Recebimento DOC	', natureza: 'Entrada', sinal: '+')
Transacao.create(tipo: 9, descricao: 'Aluguel', natureza: 'Saída', sinal: '-')
