default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: app_cnab_bycoders_development

test:
  <<: *default
  database: app_cnab_bycoders_test
  
production:
  <<: *default
  database: app_cnab_bycoders_production
